version: "3.7"
services:
  app:
    container_name: java-app-container
    image: waelkarma/javaprogram:v1
    environment:
      # postgresql_dbgmc is the container_name defined below
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_dbgmc:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8084:8084"
    volumes:
      - .:/app
    depends_on:
      - PostgreSQL
    networks:
      - spring
  PostgreSQL:
    container_name: postgresql_dbgmc
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
    # where postgres stores data in linux
      - postgres:/var/lib/postgresql/data
    networks:
      - spring
  pgadmin:
    container_name: pgadmingmc
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=wael.karma.enib@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - PostgreSQL
    networks:
      - spring
volumes:
  postgres:
  pgadmin-data:
networks:
  spring:
    driver: bridge
